name: leaf
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - rich==13.9.4
  - pytorch==2.5.1
  - torchvision==0.20.1
  - plotly==5.19.0
  - pandas==2.2.2
  - flake8==7.2.0
  - matplotlib
  - ipykernel==6.29.5